//! The IHO Sea Areas v3 name table, so `--region "<sea name>"` works without
//! the user holding a copy of the 149 MB shapefile.
//!
//! Generated by `scripts/gen_iho_areas.py`, do not edit by hand. To refresh it
//! against a new IHO release:
//!
//! ```bash
//! seastamp regions --data <IHO shapefile> -q -o areas.csv
//! scripts/gen_iho_areas.py areas.csv > src/config/iho_areas.rs
//! ```
//!
//! `crosses` marks an area whose extent runs east past 180 and continues from
//! -180. Its `min_lon` is greater than its `max_lon`, which is a box seastamp
//! cannot use, so the lookup refuses those by name rather than handing back an
//! inverted region. See `docs/src/commands/regions.md`.
//!
//! Note that an IHO area is not always the colloquial sea: S-23 splits the
//! Gulfs of Bothnia, Finland, and Riga out of the Baltic, so `--region "Baltic
//! Sea"` crops more tightly than the `baltic` preset.

use super::BBox;

/// One named IHO area: its box, and whether that box crosses the antimeridian.
pub struct IhoArea {
    pub name: &'static str,
    pub bbox: BBox,
    pub crosses: bool,
}


/// Every IHO Sea Areas v3 area, sorted by name.
pub const IHO_AREAS: [IhoArea; 101] = [
    IhoArea {
        name: "Adriatic Sea",
        bbox: BBox { min_lon: 12.0652, max_lon: 20.0208, min_lat: 39.7431, max_lat: 45.8089 },
        crosses: false,
    },
    IhoArea {
        name: "Aegean Sea",
        bbox: BBox { min_lon: 22.5316, max_lon: 28.3306, min_lat: 35.1095, max_lat: 41.0913 },
        crosses: false,
    },
    IhoArea {
        name: "Alboran Sea",
        bbox: BBox { min_lon: -5.3538, max_lon: -1.1883, min_lat: 35.0707, max_lat: 36.8415 },
        crosses: false,
    },
    IhoArea {
        name: "Andaman or Burma Sea",
        bbox: BBox { min_lon: 92.3904, max_lon: 99.1397, min_lat: 5.5343, max_lat: 17.7539 },
        crosses: false,
    },
    IhoArea {
        name: "Arabian Sea",
        bbox: BBox { min_lon: 51.0223, max_lon: 74.335, min_lat: -0.7034, max_lat: 25.5974 },
        crosses: false,
    },
    IhoArea {
        name: "Arafura Sea",
        bbox: BBox { min_lon: 130.7588, max_lon: 142.1993, min_lat: -18.0068, max_lat: -2.9027 },
        crosses: false,
    },
    IhoArea {
        name: "Arctic Ocean",
        bbox: BBox { min_lon: -180.0, max_lon: 180.0, min_lat: 71.3875, max_lat: 90.0 },
        crosses: false,
    },
    IhoArea {
        name: "Baffin Bay",
        bbox: BBox { min_lon: -82.2038, max_lon: -50.5233, min_lat: 69.617, max_lat: 82.4498 },
        crosses: false,
    },
    IhoArea {
        name: "Balearic (Iberian Sea)",
        bbox: BBox { min_lon: -0.3659, max_lon: 4.2902, min_lat: 38.6473, max_lat: 41.8748 },
        crosses: false,
    },
    IhoArea {
        name: "Bali Sea",
        bbox: BBox { min_lon: 114.3402, max_lon: 117.1657, min_lat: -8.9986, max_lat: -7.0131 },
        crosses: false,
    },
    IhoArea {
        name: "Baltic Sea",
        bbox: BBox { min_lon: 9.5223, max_lon: 23.5117, min_lat: 52.6535, max_lat: 59.9386 },
        crosses: false,
    },
    IhoArea {
        name: "Banda Sea",
        bbox: BBox { min_lon: 120.4667, max_lon: 133.1514, min_lat: -8.8645, max_lat: -0.8359 },
        crosses: false,
    },
    IhoArea {
        name: "Barentsz Sea",
        bbox: BBox { min_lon: 16.5818, max_lon: 68.5783, min_lat: 65.8828, max_lat: 81.8512 },
        crosses: false,
    },
    IhoArea {
        name: "Bass Strait",
        bbox: BBox { min_lon: 143.5325, max_lon: 149.9095, min_lat: -41.4403, max_lat: -37.4608 },
        crosses: false,
    },
    IhoArea {
        name: "Bay of Bengal",
        bbox: BBox { min_lon: 78.8982, max_lon: 95.0488, min_lat: 5.734, max_lat: 24.3777 },
        crosses: false,
    },
    IhoArea {
        name: "Bay of Biscay",
        bbox: BBox { min_lon: -7.8968, max_lon: -0.1462, min_lat: 43.2744, max_lat: 47.9878 },
        crosses: false,
    },
    IhoArea {
        name: "Bay of Fundy",
        bbox: BBox { min_lon: -67.324, max_lon: -63.3047, min_lat: 44.088, max_lat: 46.2026 },
        crosses: false,
    },
    IhoArea {
        name: "Beaufort Sea",
        bbox: BBox { min_lon: -156.6649, max_lon: -122.6528, min_lat: 67.5965, max_lat: 76.3629 },
        crosses: false,
    },
    IhoArea {
        name: "Bering Sea",
        bbox: BBox { min_lon: 161.8238, max_lon: -156.2257, min_lat: 51.3508, max_lat: 66.5629 },
        crosses: true,
    },
    IhoArea {
        name: "Bismarck Sea",
        bbox: BBox { min_lon: 141.9929, max_lon: 152.8765, min_lat: -5.962, max_lat: -1.0746 },
        crosses: false,
    },
    IhoArea {
        name: "Black Sea",
        bbox: BBox { min_lon: 27.4437, max_lon: 42.355, min_lat: 40.9088, max_lat: 47.3103 },
        crosses: false,
    },
    IhoArea {
        name: "Bristol Channel",
        bbox: BBox { min_lon: -4.9243, max_lon: -2.3454, min_lat: 50.9889, max_lat: 51.8189 },
        crosses: false,
    },
    IhoArea {
        name: "Caribbean Sea",
        bbox: BBox { min_lon: -89.4129, max_lon: -59.4216, min_lat: 7.7098, max_lat: 22.7065 },
        crosses: false,
    },
    IhoArea {
        name: "Celebes Sea",
        bbox: BBox { min_lon: 116.7183, max_lon: 125.6139, min_lat: 0.8011, max_lat: 7.8516 },
        crosses: false,
    },
    IhoArea {
        name: "Celtic Sea",
        bbox: BBox { min_lon: -11.5, max_lon: -4.1381, min_lat: 46.5006, max_lat: 52.3957 },
        crosses: false,
    },
    IhoArea {
        name: "Ceram Sea",
        bbox: BBox { min_lon: 125.9173, max_lon: 134.0316, min_lat: -5.2739, max_lat: -1.1861 },
        crosses: false,
    },
    IhoArea {
        name: "Chukchi Sea",
        bbox: BBox { min_lon: 177.4788, max_lon: -156.4799, min_lat: 65.9344, max_lat: 71.7113 },
        crosses: true,
    },
    IhoArea {
        name: "Coral Sea",
        bbox: BBox { min_lon: 141.0216, max_lon: 169.8654, min_lat: -30.0, max_lat: -6.7929 },
        crosses: false,
    },
    IhoArea {
        name: "Davis Strait",
        bbox: BBox { min_lon: -70.1432, max_lon: -44.4618, min_lat: 59.8915, max_lat: 70.0721 },
        crosses: false,
    },
    IhoArea {
        name: "East Siberian Sea",
        bbox: BBox { min_lon: 139.0318, max_lon: 180.0, min_lat: 64.3154, max_lat: 77.0971 },
        crosses: false,
    },
    IhoArea {
        name: "Eastern China Sea",
        bbox: BBox { min_lon: 118.478, max_lon: 131.1322, min_lat: 24.0576, max_lat: 33.372 },
        crosses: false,
    },
    IhoArea {
        name: "English Channel",
        bbox: BBox { min_lon: -5.7087, max_lon: 1.9309, min_lat: 48.5, max_lat: 51.166 },
        crosses: false,
    },
    IhoArea {
        name: "Flores Sea",
        bbox: BBox { min_lon: 117.1333, max_lon: 122.9389, min_lat: -8.744, max_lat: -5.5076 },
        crosses: false,
    },
    IhoArea {
        name: "Great Australian Bight",
        bbox: BBox { min_lon: 117.6142, max_lon: 146.2312, min_lat: -43.566, max_lat: -31.4637 },
        crosses: false,
    },
    IhoArea {
        name: "Greenland Sea",
        bbox: BBox { min_lon: -35.9868, max_lon: 17.4822, min_lat: 65.007, max_lat: 82.7807 },
        crosses: false,
    },
    IhoArea {
        name: "Gulf of Aden",
        bbox: BBox { min_lon: 42.5135, max_lon: 51.2867, min_lat: 10.3781, max_lat: 15.2197 },
        crosses: false,
    },
    IhoArea {
        name: "Gulf of Alaska",
        bbox: BBox { min_lon: -163.3576, max_lon: -136.6181, min_lat: 54.2983, max_lat: 61.5495 },
        crosses: false,
    },
    IhoArea {
        name: "Gulf of Aqaba",
        bbox: BBox { min_lon: 34.3273, max_lon: 35.0014, min_lat: 27.9001, max_lat: 29.5495 },
        crosses: false,
    },
    IhoArea {
        name: "Gulf of Boni",
        bbox: BBox { min_lon: 120.1888, max_lon: 121.8667, min_lat: -5.6156, max_lat: -2.5805 },
        crosses: false,
    },
    IhoArea {
        name: "Gulf of Bothnia",
        bbox: BBox { min_lon: 17.0389, max_lon: 25.4866, min_lat: 59.7209, max_lat: 67.0806 },
        crosses: false,
    },
    IhoArea {
        name: "Gulf of California",
        bbox: BBox { min_lon: -115.036, max_lon: -106.7851, min_lat: 22.8788, max_lat: 31.9496 },
        crosses: false,
    },
    IhoArea {
        name: "Gulf of Finland",
        bbox: BBox { min_lon: 22.91, max_lon: 37.4689, min_lat: 59.2146, max_lat: 62.9158 },
        crosses: false,
    },
    IhoArea {
        name: "Gulf of Guinea",
        bbox: BBox { min_lon: -7.7263, max_lon: 10.1827, min_lat: -0.936, max_lat: 6.6227 },
        crosses: false,
    },
    IhoArea {
        name: "Gulf of Mexico",
        bbox: BBox { min_lon: -98.0539, max_lon: -80.433, min_lat: 17.4068, max_lat: 31.4648 },
        crosses: false,
    },
    IhoArea {
        name: "Gulf of Oman",
        bbox: BBox { min_lon: 56.268, max_lon: 61.7825, min_lat: 22.4749, max_lat: 25.9434 },
        crosses: false,
    },
    IhoArea {
        name: "Gulf of Riga",
        bbox: BBox { min_lon: 21.7251, max_lon: 24.6168, min_lat: 56.8046, max_lat: 59.2148 },
        crosses: false,
    },
    IhoArea {
        name: "Gulf of St. Lawrence",
        bbox: BBox { min_lon: -74.8648, max_lon: -54.7034, min_lat: 44.9585, max_lat: 52.2224 },
        crosses: false,
    },
    IhoArea {
        name: "Gulf of Suez",
        bbox: BBox { min_lon: 32.3429, max_lon: 34.2278, min_lat: 27.45, max_lat: 30.0682 },
        crosses: false,
    },
    IhoArea {
        name: "Gulf of Thailand",
        bbox: BBox { min_lon: 99.1327, max_lon: 105.3623, min_lat: 5.3905, max_lat: 13.7271 },
        crosses: false,
    },
    IhoArea {
        name: "Gulf of Tomini",
        bbox: BBox { min_lon: 120.005, max_lon: 123.4102, min_lat: -1.4405, max_lat: 0.5553 },
        crosses: false,
    },
    IhoArea {
        name: "Halmahera Sea",
        bbox: BBox { min_lon: 127.5492, max_lon: 130.9317, min_lat: -1.681, max_lat: 2.487 },
        crosses: false,
    },
    IhoArea {
        name: "Hudson Bay",
        bbox: BBox { min_lon: -95.3462, max_lon: -75.8844, min_lat: 51.1436, max_lat: 66.0264 },
        crosses: false,
    },
    IhoArea {
        name: "Hudson Strait",
        bbox: BBox { min_lon: -80.9516, max_lon: -64.4322, min_lat: 55.8448, max_lat: 64.98 },
        crosses: false,
    },
    IhoArea {
        name: "Indian Ocean",
        bbox: BBox { min_lon: 20.0026, max_lon: 146.8982, min_lat: -60.0, max_lat: 10.445 },
        crosses: false,
    },
    IhoArea {
        name: "Inner Seas off the West Coast of Scotland",
        bbox: BBox { min_lon: -8.2496, max_lon: -4.4586, min_lat: 54.3364, max_lat: 58.6245 },
        crosses: false,
    },
    IhoArea {
        name: "Ionian Sea",
        bbox: BBox { min_lon: 15.0846, max_lon: 23.2247, min_lat: 36.409, max_lat: 40.5207 },
        crosses: false,
    },
    IhoArea {
        name: "Irish Sea and St. George's Channel",
        bbox: BBox { min_lon: -6.5691, max_lon: -2.6392, min_lat: 51.9041, max_lat: 55.0042 },
        crosses: false,
    },
    IhoArea {
        name: "Japan Sea",
        bbox: BBox { min_lon: 125.8014, max_lon: 142.2638, min_lat: 32.575, max_lat: 51.7473 },
        crosses: false,
    },
    IhoArea {
        name: "Java Sea",
        bbox: BBox { min_lon: 104.5271, max_lon: 119.4894, min_lat: -7.8109, max_lat: -1.5494 },
        crosses: false,
    },
    IhoArea {
        name: "Kara Sea",
        bbox: BBox { min_lon: 54.9305, max_lon: 107.6064, min_lat: 64.4323, max_lat: 81.2682 },
        crosses: false,
    },
    IhoArea {
        name: "Kattegat",
        bbox: BBox { min_lon: 9.3656, max_lon: 13.0629, min_lat: 54.6337, max_lat: 58.0775 },
        crosses: false,
    },
    IhoArea {
        name: "Labrador Sea",
        bbox: BBox { min_lon: -64.306, max_lon: -43.6749, min_lat: 47.386, max_lat: 60.3988 },
        crosses: false,
    },
    IhoArea {
        name: "Laccadive Sea",
        bbox: BBox { min_lon: 71.9824, max_lon: 80.5888, min_lat: -0.6932, max_lat: 14.7927 },
        crosses: false,
    },
    IhoArea {
        name: "Laptev Sea",
        bbox: BBox { min_lon: 93.6572, max_lon: 141.2251, min_lat: 63.6878, max_lat: 81.269 },
        crosses: false,
    },
    IhoArea {
        name: "Ligurian Sea",
        bbox: BBox { min_lon: 7.539, max_lon: 9.8521, min_lat: 42.8644, max_lat: 44.4272 },
        crosses: false,
    },
    IhoArea {
        name: "Lincoln Sea",
        bbox: BBox { min_lon: -70.1954, max_lon: -37.0055, min_lat: 81.4958, max_lat: 83.5619 },
        crosses: false,
    },
    IhoArea {
        name: "Makassar Strait",
        bbox: BBox { min_lon: 115.9545, max_lon: 120.8283, min_lat: -5.5956, max_lat: 1.325 },
        crosses: false,
    },
    IhoArea {
        name: "Malacca Strait",
        bbox: BBox { min_lon: 95.4423, max_lon: 103.5107, min_lat: 0.8573, max_lat: 8.454 },
        crosses: false,
    },
    IhoArea {
        name: "Mediterranean Sea - Eastern Basin",
        bbox: BBox { min_lon: 10.0158, max_lon: 36.2157, min_lat: 30.0681, max_lat: 37.8015 },
        crosses: false,
    },
    IhoArea {
        name: "Mediterranean Sea - Western Basin",
        bbox: BBox { min_lon: -2.1934, max_lon: 12.4242, min_lat: 35.5723, max_lat: 43.924 },
        crosses: false,
    },
    IhoArea {
        name: "Molukka Sea",
        bbox: BBox { min_lon: 123.2932, max_lon: 128.5664, min_lat: -1.8388, max_lat: 4.486 },
        crosses: false,
    },
    IhoArea {
        name: "Mozambique Channel",
        bbox: BBox { min_lon: 32.4306, max_lon: 49.242, min_lat: -26.8424, max_lat: -10.4989 },
        crosses: false,
    },
    IhoArea {
        name: "North Atlantic Ocean",
        bbox: BBox { min_lon: -83.0149, max_lon: 6.62, min_lat: -0.0026, max_lat: 68.6387 },
        crosses: false,
    },
    IhoArea {
        name: "North Pacific Ocean",
        bbox: BBox { min_lon: 128.6865, max_lon: -76.9854, min_lat: 0.0, max_lat: 58.2115 },
        crosses: true,
    },
    IhoArea {
        name: "North Sea",
        bbox: BBox { min_lon: -4.4454, max_lon: 12.0059, min_lat: 50.9954, max_lat: 61.017 },
        crosses: false,
    },
    IhoArea {
        name: "Norwegian Sea",
        bbox: BBox { min_lon: -13.5007, max_lon: 25.7887, min_lat: 60.8608, max_lat: 76.5645 },
        crosses: false,
    },
    IhoArea {
        name: "Persian Gulf",
        bbox: BBox { min_lon: 47.7024, max_lon: 57.34, min_lat: 23.959, max_lat: 31.1859 },
        crosses: false,
    },
    IhoArea {
        name: "Philippine Sea",
        bbox: BBox { min_lon: 120.1001, max_lon: 146.0533, min_lat: 2.4983, max_lat: 35.2631 },
        crosses: false,
    },
    IhoArea {
        name: "Red Sea",
        bbox: BBox { min_lon: 33.6394, max_lon: 43.5055, min_lat: 12.4563, max_lat: 28.1395 },
        crosses: false,
    },
    IhoArea {
        name: "Rio de La Plata",
        bbox: BBox { min_lon: -59.7657, max_lon: -54.943, min_lat: -36.3589, max_lat: -31.5234 },
        crosses: false,
    },
    IhoArea {
        name: "Savu Sea",
        bbox: BBox { min_lon: 118.5023, max_lon: 125.0051, min_lat: -10.9226, max_lat: -8.214 },
        crosses: false,
    },
    IhoArea {
        name: "Sea of Azov",
        bbox: BBox { min_lon: 34.5163, max_lon: 40.4297, min_lat: 45.1009, max_lat: 47.3764 },
        crosses: false,
    },
    IhoArea {
        name: "Sea of Marmara",
        bbox: BBox { min_lon: 26.1742, max_lon: 29.9422, min_lat: 39.9989, max_lat: 41.2329 },
        crosses: false,
    },
    IhoArea {
        name: "Sea of Okhotsk",
        bbox: BBox { min_lon: 135.1719, max_lon: 167.1682, min_lat: 43.2166, max_lat: 62.9155 },
        crosses: false,
    },
    IhoArea {
        name: "Seto Naikai or Inland Sea",
        bbox: BBox { min_lon: 130.8369, max_lon: 135.6697, min_lat: 33.1973, max_lat: 34.8645 },
        crosses: false,
    },
    IhoArea {
        name: "Singapore Strait",
        bbox: BBox { min_lon: 103.3457, max_lon: 104.5826, min_lat: 1.0717, max_lat: 1.7004 },
        crosses: false,
    },
    IhoArea {
        name: "Skagerrak",
        bbox: BBox { min_lon: 6.9982, max_lon: 11.9166, min_lat: 57.0988, max_lat: 59.9191 },
        crosses: false,
    },
    IhoArea {
        name: "Solomon Sea",
        bbox: BBox { min_lon: 146.9454, max_lon: 162.3484, min_lat: -11.8825, max_lat: -4.8333 },
        crosses: false,
    },
    IhoArea {
        name: "South Atlantic Ocean",
        bbox: BBox { min_lon: -69.6008, max_lon: 20.009, min_lat: -60.0, max_lat: 0.0751 },
        crosses: false,
    },
    IhoArea {
        name: "South China Sea",
        bbox: BBox { min_lon: 102.2385, max_lon: 122.1513, min_lat: -3.2287, max_lat: 25.5673 },
        crosses: false,
    },
    IhoArea {
        name: "South Pacific Ocean",
        bbox: BBox { min_lon: 130.1113, max_lon: -67.2667, min_lat: -60.0, max_lat: 3.3911 },
        crosses: true,
    },
    IhoArea {
        name: "Southern Ocean",
        bbox: BBox { min_lon: -180.0, max_lon: 180.0, min_lat: -85.5625, max_lat: -60.0 },
        crosses: false,
    },
    IhoArea {
        name: "Strait of Gibraltar",
        bbox: BBox { min_lon: -6.0325, max_lon: -5.2787, min_lat: 35.776, max_lat: 36.1869 },
        crosses: false,
    },
    IhoArea {
        name: "Sulu Sea",
        bbox: BBox { min_lon: 116.7397, max_lon: 123.4205, min_lat: 5.0201, max_lat: 13.4452 },
        crosses: false,
    },
    IhoArea {
        name: "Tasman Sea",
        bbox: BBox { min_lon: 146.8726, max_lon: 175.287, min_lat: -50.8669, max_lat: -30.0 },
        crosses: false,
    },
    IhoArea {
        name: "The Coastal Waters of Southeast Alaska and British Columbia",
        bbox: BBox { min_lon: -137.1302, max_lon: -122.1499, min_lat: 47.0238, max_lat: 59.4972 },
        crosses: false,
    },
    IhoArea {
        name: "The Northwestern Passages",
        bbox: BBox { min_lon: -128.0056, max_lon: -69.0901, min_lat: 63.7574, max_lat: 81.7018 },
        crosses: false,
    },
    IhoArea {
        name: "Timor Sea",
        bbox: BBox { min_lon: 122.8523, max_lon: 132.9313, min_lat: -15.796, max_lat: -8.1828 },
        crosses: false,
    },
    IhoArea {
        name: "Tyrrhenian Sea",
        bbox: BBox { min_lon: 8.6485, max_lon: 16.2231, min_lat: 37.8015, max_lat: 44.1095 },
        crosses: false,
    },
    IhoArea {
        name: "White Sea",
        bbox: BBox { min_lon: 32.1325, max_lon: 45.6716, min_lat: 60.951, max_lat: 68.6568 },
        crosses: false,
    },
    IhoArea {
        name: "Yellow Sea",
        bbox: BBox { min_lon: 117.5162, max_lon: 127.4589, min_lat: 33.276, max_lat: 41.1592 },
        crosses: false,
    },
];
