#!/usr/bin/env python3
"""Generate src/config/iho_areas.rs from a `seastamp regions` table.

The IHO Sea Areas shapefile is 149 MB and is not shipped, but its name-to-box
table is only a few kilobytes, so it is baked into the binary and lets
`--region "<sea name>"` work without the user holding a copy.

Usage:
    seastamp regions --data <IHO shapefile> -q -o areas.csv
    scripts/gen_iho_areas.py areas.csv > src/config/iho_areas.rs

Reads the CSV `regions` writes (name, min_lon, max_lon, min_lat, max_lat,
crosses_antimeridian) and emits a sorted const array. Coordinates are rounded to
four decimals, about 10 m, which is far finer than a crop box needs and keeps
the generated source readable.
"""

import csv
import sys

DECIMALS = 4

HEADER = '''//! The IHO Sea Areas v3 name table, so `--region "<sea name>"` works without
//! the user holding a copy of the 149 MB shapefile.
//!
//! Generated by `scripts/gen_iho_areas.py`, do not edit by hand. To refresh it
//! against a new IHO release:
//!
//! ```bash
//! seastamp regions --data <IHO shapefile> -q -o areas.csv
//! scripts/gen_iho_areas.py areas.csv > src/config/iho_areas.rs
//! ```
//!
//! `crosses` marks an area whose extent runs east past 180 and continues from
//! -180. Its `min_lon` is greater than its `max_lon`, which is a box seastamp
//! cannot use, so the lookup refuses those by name rather than handing back an
//! inverted region. See `docs/src/commands/regions.md`.
//!
//! Note that an IHO area is not always the colloquial sea: S-23 splits the
//! Gulfs of Bothnia, Finland, and Riga out of the Baltic, so `--region "Baltic
//! Sea"` crops more tightly than the `baltic` preset.

use super::BBox;

/// One named IHO area: its box, and whether that box crosses the antimeridian.
pub struct IhoArea {
    pub name: &'static str,
    pub bbox: BBox,
    pub crosses: bool,
}
'''


def num(text: str) -> str:
    """A coordinate as Rust source, rounded and always with a decimal point."""
    v = round(float(text), DECIMALS) + 0.0  # + 0.0 turns -0.0 into 0.0
    return repr(v)


def main() -> int:
    if len(sys.argv) != 2:
        sys.stderr.write(__doc__)
        return 2
    with open(sys.argv[1], newline="") as fh:
        rows = sorted(csv.DictReader(fh), key=lambda r: r["name"])
    if not rows:
        sys.stderr.write("no rows in %s\n" % sys.argv[1])
        return 1

    out = [HEADER]
    out.append("\n/// Every IHO Sea Areas v3 area, sorted by name.")
    out.append("pub const IHO_AREAS: [IhoArea; %d] = [" % len(rows))
    for r in rows:
        name = r["name"].replace("\\", "\\\\").replace('"', '\\"')
        out.append("    IhoArea {")
        out.append('        name: "%s",' % name)
        out.append(
            "        bbox: BBox { min_lon: %s, max_lon: %s, min_lat: %s, max_lat: %s },"
            % (num(r["min_lon"]), num(r["max_lon"]), num(r["min_lat"]), num(r["max_lat"]))
        )
        out.append(
            "        crosses: %s,"
            % ("true" if r["crosses_antimeridian"].lower() == "true" else "false")
        )
        out.append("    },")
    out.append("];")
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
